In [1]:
import numpy as np

In [4]:
x=np.array([1,2,3,4,5])

print()
print("x = \n",x)
print()

print("first element of the array : ",x[0])
print("second element of the array: ",x[1])
print("last element of the array: ",x[4])
print()
print("first element of the array : ",x[-5])
print("second element of the array :",x[-4])
print("last element of the array :",x[-1])


x = 
 [1 2 3 4 5]

first element of the array :  1
second element of the array:  2
last element of the array:  5

first element of the array :  1
second element of the array : 2
last element of the array : 5


In [7]:
x=np.array([1,2,3,4,5])

print()
print("Original x = \n",x)
print()


x[3]=10

print()
print("Modified x = \n",x)
print()



Original x = 
 [1 2 3 4 5]


Modified x = 
 [ 1  2  3 10  5]



In [10]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print()
print("x = \n",x)
print()

print("first element of the array",x[0][0])
print("second element of the array",x[0][1])
print("last element of array",x[3][2])


x = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

first element of the array 1
second element of the array 2
last element of array 12


In [11]:
# modift rank2 array
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print("Original x = \n",x)
print()

x[0][0]=20

print()
print("Modified x= \n",x)
print()


Original x = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Modified x= 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]



In [16]:
x=np.array([1,2,3,4,5])
y=np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print("Original x=\n",x)
print()

x=np.delete(x,[0,4])

print()
print("Modified x=\n",x)
print()

print()
print("Original y=\n",y)
print()


w=np.delete(y,0,axis=0)

print()
print("Modified w=\n",w)
print()

print()
print("Original y=\n",y)
print()

v=np.delete(y,[0,2],axis=1)

print()
print("Modified v=\n",v)
print()



Original x=
 [1 2 3 4 5]


Modified x=
 [2 3 4]


Original y=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Modified w=
 [[4 5 6]
 [7 8 9]]


Original y=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Modified v=
 [[2]
 [5]
 [8]]



In [38]:
x=np.array([1,2,3,4,5])

y=np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print("Original x = \n",x)
print()

x = np.append(x,6)

print()
print("Modified x = \n",x)
print()

x=np.append(x,[7,8])

print()
print("Modified x = \n",x)
print()


print()
print("Original y = \n",y)
print()


w=np.append(y,[[10,11,12]],axis=0)

print()
print("Modified w = \n",w)
print()

q=np.append(y,[[7],[8]],axis=1)


print()
print("Modified q = \n",q)
print()


Original x = 
 [1 2 3 4 5]


Modified x = 
 [1 2 3 4 5 6]


Modified x = 
 [1 2 3 4 5 6 7 8]


Original y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Modified w = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Modified q = 
 [1 2 3 4 5 6 7 8 9 7 8]



In [52]:
x=np.array([1,2,5,6,7])
y=np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print("x = \n",x)
print()

x=np.insert(x,2,[3,4])

print()
print("modified x = \n",x)
print()

print()
print("y = \n",y)
print()

w=np.insert(y,1,[9,8,7],axis=0)

print()
print("modified w = \n",w)
print()

print()
print("y = \n",y)
print()

v=np.insert(y,3,5,axis=1)

print()
print("modified v = \n",v)
print()



x = 
 [1 2 5 6 7]


modified x = 
 [1 2 3 4 5 6 7]


y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


modified w = 
 [[1 2 3]
 [9 8 7]
 [4 5 6]
 [7 8 9]]


y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


modified v = 
 [[1 2 3 5]
 [4 5 6 5]
 [7 8 9 5]]



In [57]:
x=np.array([1,2])
y=np.array([[3,4],[5,6]])

print()
print("x = \n",x)
print()

print()
print("y = \n",y)
print()

w=np.vstack((x,y))

print()
print("w = \n",w)
print()

v=np.hstack((y,x.reshape(2,1)))


print()
print("v = \n",v)
print()


x = 
 [1 2]


y = 
 [[3 4]
 [5 6]]


w = 
 [[1 2]
 [3 4]
 [5 6]]


v = 
 [[3 4 1]
 [5 6 2]]

