In [1]:
import numpy as np

In [16]:
x=np.array([1,2,3,4,5])
y=np.array([6,8,7,9,10])

print()
print("x = \n",x)
print()

print()
print("y = \n",y)
print()

print("x+y = ",x+y)
print("np.add(x,y)= ",np.add(x,y))
print()
print("x-y= ",x-y)
print("np.subtract(x,y)= ",np.subtract(x,y))
print()
print("x*y=",x*y)
print("np.multiply=",np.multiply(x,y))
print()
print("x/y=",x/y)
print("np.divide(x,y)=",np.divide(x,y))


x = 
 [1 2 3 4 5]


y = 
 [ 6  8  7  9 10]

x+y =  [ 7 10 10 13 15]
np.add(x,y)=  [ 7 10 10 13 15]

x-y=  [-5 -6 -4 -5 -5]
np.subtract(x,y)=  [-5 -6 -4 -5 -5]

x*y= [ 6 16 21 36 50]
np.multiply= [ 6 16 21 36 50]

x/y= [0.16666667 0.25       0.42857143 0.44444444 0.5       ]
np.divide(x,y)= [0.16666667 0.25       0.42857143 0.44444444 0.5       ]


In [18]:
x=np.array([1,2,3,4]).reshape(2,2)

y=np.array([5,6,7,8]).reshape(2,2)

print()
print("x = \n",x)
print()

print()
print("y = \n",y)
print()

print()
print("x+y = ",x+y)
print("np.add(x,y)=",np.add(x,y))

print()
print("x-y = ",x-y)
print("np.subtract(x,y)",np.subtract(x,y))

print()
print("x*y = ",x*y)
print("np.multiply=",np.multiply(x,y))

print()
print("x/y = ",x/y)
print("np.divide(x,y)=",np.divide(x,y))


x = 
 [[1 2]
 [3 4]]


y = 
 [[5 6]
 [7 8]]


x+y =  [[ 6  8]
 [10 12]]
np.add(x,y)= [[ 6  8]
 [10 12]]

x-y =  [[-4 -4]
 [-4 -4]]
np.subtract(x,y) [[-4 -4]
 [-4 -4]]

x*y =  [[ 5 12]
 [21 32]]
np.multiply= [[ 5 12]
 [21 32]]

x/y =  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
np.divide(x,y)= [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [19]:
x=np.array([1,2,3,4])

print()
print("x = \n",x)
print()

print()
print("np.exp(x) = ",np.exp(x))
print("np.sqrt(x) =",np.sqrt(x))
print("np.power(x,2)",np.power(x,2))



x = 
 [1 2 3 4]


np.exp(x) =  [ 2.71828183  7.3890561  20.08553692 54.59815003]
np.sqrt(x) = [1.         1.41421356 1.73205081 2.        ]
np.power(x,2) [ 1  4  9 16]


In [28]:
x=np.array([[1,2],[3,4]])

print()
print("x = \n",x)
print()

print()
print("average of elements  ",np.mean(x))
print("average of elements in column =",np.mean(x,axis=0))
print("average of elements in row =",np.mean(x,axis=1))

print("sum of all elements =",np.sum(x))
print("sum of all elements in columns =",np.sum(x,axis=0))
print("sum of all elements in row=",np.sum(x,axis=1))

print("standard deviation of all elements =",np.std(x))
print("standard deviation of all elements in column",np.std(x,axis=0))
print("standard deviation of all elements in row",np.std(x,axis=1))

print("median of elements =",np.median(x))
print("median of elements of column",np.median(x,axis=0))
print("median of elements of row",np.median(x,axis=1))

print("max of elements",np.max(x))
print("max of elements of column",np.max(x,axis=0))
print("max of elements of row",np.max(x,axis=1))


print("min of elements",np.min(x))
print("min of elements of column",np.min(x,axis=0))
print("min of elements of row",np.min(x,axis=1))


x = 
 [[1 2]
 [3 4]]


average of elements   2.5
average of elements in column = [2. 3.]
average of elements in row = [1.5 3.5]
sum of all elements = 10
sum of all elements in columns = [4 6]
sum of all elements in row= [3 7]
standard deviation of all elements = 1.118033988749895
standard deviation of all elements in column [1. 1.]
standard deviation of all elements in row [0.5 0.5]
median of elements = 2.5
median of elements of column [2. 3.]
median of elements of row [1.5 3.5]
max of elements 4
max of elements of column [3 4]
max of elements of row [2 4]


In [31]:
x=np.array([[1,2],[3,4]])

print()
print("x = \n",x)
print()

print("sum =",3+x)
print("sub= ",3-x)
print("mul= ",3*x)
print("div= ",3/x)



x = 
 [[1 2]
 [3 4]]

sum = [[4 5]
 [6 7]]
sub=  [[ 2  1]
 [ 0 -1]]
mul=  [[ 3  6]
 [ 9 12]]
div=  [[3.   1.5 ]
 [1.   0.75]]


In [32]:
x=np.array([1,2,3])
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
z=np.array([1,2,3]).reshape(3,1)
print()
print("x =\n",x)
print()

print("x+y",x+y)
print("z+y",z+y)



x =
 [1 2 3]

x+y [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
z+y [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [46]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

x = np.ones((4,4))

print()
print("x = \n",x)
print()
y=np.array([1,2,3,4]).reshape(4,1)

print()
print("y = \n",y)
print()
print()
print("required matrix= \n",y*x)
print()


x = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


y = 
 [[1]
 [2]
 [3]
 [4]]


required matrix= 
 [[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]



In [48]:
x=np.ones((4,4))*np.arange(1,5)
print()
print("x = \n",x)
print()


x = 
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]

