In [1]:
import numpy as np

In [15]:
x=np.arange(24).reshape(6,4)

print()
print("x= \n",x)
print()


x= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [16]:
print("elements those are greater than 10",x[x>10])
print("eleements those are lesss than 10",x[x<10])
print("elements those are betwwen 10 and 17",x[(x>10) & (x<17)])

elements those are greater than 10 [11 12 13 14 15 16 17 18 19 20 21 22 23]
eleements those are lesss than 10 [0 1 2 3 4 5 6 7 8 9]
elements those are betwwen 10 and 17 [11 12 13 14 15 16]


In [17]:
x[(x>10)&(x<17)]=-1
print()
print("x= \n",x)
print()


x= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 -1]
 [-1 -1 -1 -1]
 [-1 17 18 19]
 [20 21 22 23]]



In [24]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,2,8,4])

print("intersection of x and y",np.intersect1d(x,y))
print("difference of x and y",np.setdiff1d(x,y))
print("union of x and y",np.union1d(x,y))

intersection of x and y [2 4]
difference of x and y [1 3 5]
union of x and y [1 2 3 4 5 6 7 8]


In [33]:
x=np.random.randint(0,11,size=[10,])

print()
print("x= \n",x)
print()

print()
print("sorted = \n",np.sort(x))
print()

print()
print("x= \n",x)
print()

print()
print("x= \n",np.sort(np.unique(x)))
print()

print()
print("x= \n",x)
print()


x= 
 [ 2  5 10  8  8  5  8  7  3  0]


sorted = 
 [ 0  2  3  5  5  7  8  8  8 10]


x= 
 [ 2  5 10  8  8  5  8  7  3  0]


x= 
 [ 0  2  3  5  7  8 10]


x= 
 [ 2  5 10  8  8  5  8  7  3  0]



In [31]:
x=np.random.randint(0,11,size=(10,))

print()
print("x= \n",x)
print()

x.sort()

print()
print("x= \n",x)
print()




x= 
 [ 1  6  3  8  2  8  0  0  6 10]


x= 
 [ 0  0  1  2  3  6  6  8  8 10]



In [38]:
x=np.random.randint(1,11,size=(5,4))

print()
print("x= \n",x)
print()

w=np.sort(x,axis=0)

print()
print("w= \n",w)
print()

v=np.sort(x,axis=1)

print()
print("v= \n",v)
print()


x= 
 [[ 6 10  7  3]
 [ 7 10  4  7]
 [ 5  4  9  8]
 [ 6  5  7  1]
 [ 7  8 10  6]]


w= 
 [[ 5  4  4  1]
 [ 6  5  7  3]
 [ 6  8  7  6]
 [ 7 10  9  7]
 [ 7 10 10  8]]


v= 
 [[ 3  6  7 10]
 [ 4  7  7 10]
 [ 4  5  8  9]
 [ 1  5  6  7]
 [ 6  7  8 10]]

