In [1]:
import numpy as np

In [2]:
x=np.arange(24).reshape(6,4)

print()
print("x= \n",x)
print()


x= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [3]:
print("elements those are greater than 10",x[x>10])
print("eleements those are lesss than 10",x[x<10])
print("elements those are betwwen 10 and 17",x[(x>10) & (x<17)])

elements those are greater than 10 [11 12 13 14 15 16 17 18 19 20 21 22 23]
eleements those are lesss than 10 [0 1 2 3 4 5 6 7 8 9]
elements those are betwwen 10 and 17 [11 12 13 14 15 16]


In [4]:
x[(x>10)&(x<17)]=-1
print()
print("x= \n",x)
print()


x= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 -1]
 [-1 -1 -1 -1]
 [-1 17 18 19]
 [20 21 22 23]]



In [5]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,2,8,4])

print("intersection of x and y",np.intersect1d(x,y))
print("difference of x and y",np.setdiff1d(x,y))
print("union of x and y",np.union1d(x,y))

intersection of x and y [2 4]
difference of x and y [1 3 5]
union of x and y [1 2 3 4 5 6 7 8]


In [6]:
x=np.random.randint(0,11,size=[10,])

print()
print("x= \n",x)
print()

print()
print("sorted = \n",np.sort(x))
print()

print()
print("x= \n",x)
print()

print()
print("x= \n",np.sort(np.unique(x)))
print()

print()
print("x= \n",x)
print()


x= 
 [ 7 10  6  6  3  2  7 10  7  8]


sorted = 
 [ 2  3  6  6  7  7  7  8 10 10]


x= 
 [ 7 10  6  6  3  2  7 10  7  8]


x= 
 [ 2  3  6  7  8 10]


x= 
 [ 7 10  6  6  3  2  7 10  7  8]



In [7]:
x=np.random.randint(0,11,size=(10,))

print()
print("x= \n",x)
print()

x.sort()

print()
print("x= \n",x)
print()




x= 
 [1 0 7 3 3 5 6 7 3 1]


x= 
 [0 1 1 3 3 3 5 6 7 7]



In [8]:
x=np.random.randint(1,11,size=(5,4))

print()
print("x= \n",x)
print()

w=np.sort(x,axis=0)

print()
print("w= \n",w)
print()

v=np.sort(x,axis=1)

print()
print("v= \n",v)
print()


x= 
 [[ 6 10  7  8]
 [10  1  4  4]
 [10  9  4  3]
 [ 8  7  7  9]
 [ 8 10  5  8]]


w= 
 [[ 6  1  4  3]
 [ 8  7  4  4]
 [ 8  9  5  8]
 [10 10  7  8]
 [10 10  7  9]]


v= 
 [[ 6  7  8 10]
 [ 1  4  4 10]
 [ 3  4  9 10]
 [ 7  7  8  9]
 [ 5  8  8 10]]



In [12]:
# practice
x=np.arange(20).reshape(5,4)

print()
print("x = \n",x)
print()

print("element greater than ",x[x>10])
print("elements less than,x",x[x<10])
print("elements between 10 and 17",x[(x>10)&(x<17)])


x = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

element greater than  [11 12 13 14 15 16 17 18 19]
elements less than,x [0 1 2 3 4 5 6 7 8 9]
elements between 10 and 17 [11 12 13 14 15 16]


In [18]:
x=np.array([1,2,3,4,5])
y=np.array([2,4,6,7,8])

print("intersect ",np.intersect1d(x,y))
print("differ",np.setdiff1d(x,y))
print("union",np.union1d(x,y))

intersect  [2 4]
differ [1 3 5]
union [1 2 3 4 5 6 7 8]


In [25]:
x=np.random.randint(0,11,size=[10,])

print()
print("x = \n",x)
print()

w=np.sort(x)

print()
print("w = \n",w)
print()





print()
print("x = \n",x)
print()

x.sort()
print()
print("x = \n",x)
print()


x = 
 [3 6 9 8 1 9 7 2 8 2]


w = 
 [1 2 2 3 6 7 8 8 9 9]


x = 
 [3 6 9 8 1 9 7 2 8 2]


x = 
 [1 2 2 3 6 7 8 8 9 9]



In [27]:
x=np.random.randint(0,21,size=[5,4])

print()
print("x = \n",x)
print()

x=np.sort(x,axis=0)

print()
print("x = \n",x)
print()

x=np.sort(x,axis=1)

print()
print("x = \n",x)
print()


x = 
 [[ 2 19 14 20]
 [16  5 11  3]
 [10  1  4  6]
 [19  5 11  2]
 [20 16  9 12]]


x = 
 [[ 2  1  4  2]
 [10  5  9  3]
 [16  5 11  6]
 [19 16 11 12]
 [20 19 14 20]]


x = 
 [[ 1  2  2  4]
 [ 3  5  9 10]
 [ 5  6 11 16]
 [11 12 16 19]
 [14 19 20 20]]

