In [1]:
import numpy as np

In [2]:
# we create a numpy array of zeros with 3*4
x=np.zeros((3,4))

In [3]:
# print the array

print()
print(x)
print()


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [4]:
print("shape of x: ",x.shape)
print("object of class ",type(x))
print("elements of type in x: ",x.dtype)
print("no of elemts in x: ",x.size)

shape of x:  (3, 4)
object of class  <class 'numpy.ndarray'>
elements of type in x:  float64
no of elemts in x:  12


In [12]:
# we crate a matrix of 3*4 wuth ones
x=np.ones((3,2))

In [13]:
# lets prints the ones matrix
print()
print("x = \n",x)
print()



x = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]



In [15]:
print("shape od matrix x: ",x.shape)
print("x is object of ",type(x))
print("elements in matrix of ones is ",x.dtype)
print("no of elemnts in matrix x ",x.size)

shape od matrix x:  (3, 2)
x is object of  <class 'numpy.ndarray'>
elements in matrix of ones is  float64
no of elemnts in matrix x  6


In [22]:
# lets create matrix with desired number
x=np.full((3,4),5)

In [23]:
# print the matrix
print()
print("x = \n",x)
print()


x = 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]



In [24]:
print("the shape of matrix ",x.shape)
print("the object of matrix x ",type(x))
print("the lements of type ",x.dtype)
print("the no of elements in matrix ",x.size)

the shape of matrix  (3, 4)
the object of matrix x  <class 'numpy.ndarray'>
the lements of type  int64
the no of elements in matrix  12


In [30]:
# we create a identity matrix
x=np.eye(5)

In [31]:
# lets print the identity matrix
print()
print("x = \n",x)
print()


x = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



In [32]:
print("the shape of identity matrix ",x.shape)
print("the matrix object of ",type(x))
print("the elements of matrix is",x.dtype)
print("the size of matrix",x.size)

the shape of identity matrix  (5, 5)
the matrix object of  <class 'numpy.ndarray'>
the elements of matrix is float64
the size of matrix 25


In [34]:
# create a diagonal matrix where its diagonal contains 10,20,30,40
x=np.diag([10,20,30,40])

In [35]:
# print the matrix
print()
print("x = \n",x)
print()


x = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]



In [37]:
print("the matrix of shape",x.shape)
print("the matix of object of ",type(x))
print("the elements of matrix ",x.dtype)
print("the size of matrix is ",x.size)

the matrix of shape (4, 4)
the matix of object of  <class 'numpy.ndarray'>
the elements of matrix  int64
the size of matrix is  16


In [38]:
#lets create a matrix with range 10
x=np.arange(10)

In [39]:
# lets print the matix
print()
print("x = \n",x)
print()


x = 
 [0 1 2 3 4 5 6 7 8 9]



In [41]:
print("the dimension of x",x.shape)
print("the object of ",type(x))
print("the eleemnt are type of ",x.dtype)
print("the size of matrix is ",x.size)

the dimension of x (10,)
the object of  <class 'numpy.ndarray'>
the eleemnt are type of  int64
the size of matrix is  10


In [43]:
# create a matrix with in range of 4 and 10
x=np.arange(4,10)

In [45]:
# print the arrat
print()
print("x - \n",x)
print()


x - 
 [4 5 6 7 8 9]



In [46]:
print("the shape od x ",x.shape)
print("the object type of x ",type(x))
print("the elemnents of type ",x.dtype)
print("no of elements in x ",x.size)



the shape od x  (6,)
the object type of x  <class 'numpy.ndarray'>
the elemnents of type  int64
no of elements in x  6


In [49]:
x=np.arange(1,14,3)

In [50]:
# print the matrix array
print()
print("x = \n",x)
print()


x = 
 [ 1  4  7 10 13]



In [52]:
print("the shape od x ",x.shape)
print("the object of x ",type(x))
print("the elements of type ",x.dtype)
print("the size of x is ",x.size)

the shape od x  (5,)
the object of x  <class 'numpy.ndarray'>
the elements of type  int64
the size of x is  5


In [54]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x=np.linspace(0,25,10)

In [55]:
# lets print matrix
print()
print("x = \n",x)
print()


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]



In [56]:
print("the shape od x ",x.shape)
print("the object of x ",type(x))
print("the elements of type ",x.dtype)
print("the size of x is ",x.size)

the shape od x  (10,)
the object of x  <class 'numpy.ndarray'>
the elements of type  float64
the size of x is  10


In [58]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25. with exclued endpoints
x=np.linspace(1,25,10,endpoint=False)

In [59]:
# lets print matrix
print()
print("x = \n",x)
print()


x = 
 [ 1.   3.4  5.8  8.2 10.6 13.  15.4 17.8 20.2 22.6]



In [60]:
print("the shape od x ",x.shape)
print("the object of x ",type(x))
print("the elements of type ",x.dtype)
print("the size of x is ",x.size)

the shape od x  (10,)
the object of x  <class 'numpy.ndarray'>
the elements of type  float64
the size of x is  10


In [63]:
x=np.arange(20)

# lets print matrix
print()
print("x = \n",x)
print()

# reshape
x=np.reshape(x,(4,5))

# lets print matrix
print()
print("reshaped x = \n",x)
print()

print("the shape od x ",x.shape)
print("the object of x ",type(x))
print("the elements of type ",x.dtype)
print("the size of x is ",x.size)


x = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

the shape od x  (4, 5)
the object of x  <class 'numpy.ndarray'>
the elements of type  int64
the size of x is  20


In [64]:
x=np.arange(20).reshape(4,5)

# lets print matrix
print()
print("reshaped x = \n",x)
print()

print("the shape od x ",x.shape)
print("the object of x ",type(x))
print("the elements of type ",x.dtype)
print("the size of x is ",x.size)


reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

the shape od x  (4, 5)
the object of x  <class 'numpy.ndarray'>
the elements of type  int64
the size of x is  20


In [65]:
x=np.linspace(1,50,10,endpoint=False).reshape(5,2)

# lets print matrix
print()
print("reshaped x = \n",x)
print()


reshaped x = 
 [[ 1.   5.9]
 [10.8 15.7]
 [20.6 25.5]
 [30.4 35.3]
 [40.2 45.1]]



In [67]:
# We print information about X
print('X has dimensions:', x.shape)
print('X is an object of type:', type(x))
print('The elements in X are of type:', x.dtype)

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [70]:
x=np.random.random((3,3))

In [72]:

# lets print matrix
print()
print("x = \n",x)
print()

# We print information about X
print('X has dimensions:', x.shape)
print('X is an object of type:', type(x))
print('The elements in X are of type:', x.dtype)


x = 
 [[0.85832226 0.18720737 0.00579439]
 [0.29274508 0.08223493 0.22126709]
 [0.16297884 0.15303392 0.72887656]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [78]:
x=np.random.randint(4,15,size=(3,2))

In [79]:
# lets print matrix
print()
print("x = \n",x)
print()

# We print information about X
print('X has dimensions:', x.shape)
print('X is an object of type:', type(x))
print('The elements in X are of type:', x.dtype)


x = 
 [[ 5  9]
 [ 9 13]
 [10 13]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [80]:
x=np.random.normal(0,0.1,size=(1000,1000))

In [81]:
print()
print("x = \n",x)
print()


x = 
 [[-0.04489157 -0.01639483 -0.08178703 ...  0.06707917  0.14314588
   0.14831297]
 [ 0.08111334 -0.1157932   0.27309628 ... -0.08960292  0.00495384
   0.00843463]
 [-0.07393267 -0.02213371 -0.01134561 ... -0.23463924  0.007502
   0.04481733]
 ...
 [-0.00482427 -0.32182729 -0.04622694 ... -0.1491738  -0.06103225
  -0.0590376 ]
 [ 0.10041439  0.06725322  0.15431799 ... -0.12870653  0.14154605
  -0.12286401]
 [-0.09715113  0.17692776  0.25071539 ... -0.15200925 -0.20907853
   0.01678853]]



In [82]:
# We print information about X
print('X has dimensions:', x.shape)
print('X is an object of type:', type(x))
print('The elements in X are of type:', x.dtype)

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [83]:
print("mean= ",x.mean())

mean=  -6.99318685058916e-05


In [84]:
print("max ",x.max())
print("min ",x.min())

max  0.4759637485635466
min  -0.48696669945483184


In [ ]:
print("positive",x>0)
print("negative",x<)