In [4]:
# We import NumPy into Python
import numpy as np

In [5]:
# We create a 1D ndarray that contains only integers
x=np.array([1,2,3,4,5])

In [6]:
# Let's print the ndarray we just created using the print() command
print()
print("x =",x)
print()

x = [1 2 3 4 5]


In [11]:
# We print information about x
print("x has n dimensions:",x.shape)
print("x is a object type of:",type(x))
print("the elements of x are type:",x.dtype)

x has n dimensions: (5,)
x is a object type of: <class 'numpy.ndarray'>
the elements of x are type: int64


In [14]:
# We create a 1D ndarray that contains only string
x=np.array(["sujay","chandra","GAN","CNN"])

In [15]:
# Let's print the ndarray we just created using the print() command
print()
print("x = ",x)
print()


x =  ['sujay' 'chandra' 'GAN' 'CNN']



In [16]:
# We print information about x
print("x has ndimensions:",x.shape)
print("x is a object type of:",type(x))
print("elements of x are type:",x.dtype)

x has ndimensions: (4,)
x is a object type of: <class 'numpy.ndarray'>
elements of x are type: <U7


In [26]:
#we create a 1d arrray that contains string and integers
x=np.array([1,2,"sujay","chandra"])

In [27]:
#lets print the ndarray we just created using print command
print()
print(x)
print()


['1' '2' 'sujay' 'chandra']



In [29]:
#we print the information of x
print("x has the ndimesnions:",x.shape)
print("x is the object type of:",type(x))
print("elements of the x are type of:",x.dtype)

x has the ndimesnions: (4,)
x is the object type of: <class 'numpy.ndarray'>
elements of the x are type of: <U21


In [30]:
#we create a rank2(2d) array thar contains only integers
y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [32]:
#lets print the ndarray we just created using the print command
print()
print("y = \n",y)
print()


y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



In [35]:
#we print information of y
print("the ndimensions of y array is:",y.shape)
print("y is object class of:",type(y))
print("elements in are type of:",y.dtype)
print("number of elements in y are:",y.size)

the ndimensions of y array is: (4, 3)
y is object class of: <class 'numpy.ndarray'>
elements in are type of: int64
number of elements in y are: 12


In [36]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])


In [37]:
print("the elements x are type of: ",x.dtype)
print("the elements y are type of: ",y.dtype)
print("the elements z are type of: ",z.dtype)


the elements x are type of:  int64
the elements y are type of:  float64
the elements z are type of:  float64


In [38]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x=np.array([10.0,20,30.0,40],dtype=np.int64)

In [39]:
#lets print the ndarray we just created using the print command
print()
print("x :",x)
print()


x : [10 20 30 40]



In [40]:
# the elements in the xarray are type of
print("the elements in x are ",x.dtype)

the elements in x are  int64


In [42]:
#create a x array 
x=np.array([1,2,3,4,5])

In [43]:
# save the array in file in current directory
np.save("my_array",x)

In [47]:
# now get the array from saved file with extension
y=np.load("my_array.npy")

print()
print(y)
print()

# print the type of elements
print("the elemnts are type of ",y.dtype)
print("the object of class of y is", type(y))


[1 2 3 4 5]

the elemnts are type of  int64
the object of class of y is <class 'numpy.ndarray'>
