In [1]:
import numpy as np

In [2]:
x=np.arange(20).reshape((4,5))

print()
print("x = \n",x)
print()


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [3]:
z=x[1:4,2:5]

print()
print("z = \n",z)
print()


z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



In [4]:
z=x[1:,2:]
print()
print("z = \n",z)
print()


z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



In [5]:
z=x[1:,2:5]
print()
print("z = \n",z)
print()


z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



In [6]:
v=x[2,:]
print()
print("v = \n",v)
print()


v = 
 [10 11 12 13 14]



In [7]:
c=x[:,3]

print()
print("c = \n",c)
print()


c = 
 [ 3  8 13 18]



In [8]:
b=x[:,2]

print()
print("b = \n",b)
print()


b = 
 [ 2  7 12 17]



In [9]:
r=x[:,2:3]
print()
print("r = \n",r)
print()


r = 
 [[ 2]
 [ 7]
 [12]
 [17]]



In [10]:
x=np.arange(20).reshape(4,5)

print()
print("x = \n",x)
print()

z=x[1:4,2:5]

print()
print("z = \n",z)
print()

z[2][2]=555

print()
print("x = \n",x)
print()


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


x = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



In [11]:
x=np.arange(20).reshape(4,5)

z=np.copy(x[1:,2:5])
z[2][2]=555

v=x[1:4,2:5].copy()
v[2][2]=444

print()
print("x = \n",x)
print()

print()
print("z = \n",z)
print()

print()
print("v = \n",v)
print()



x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


v = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]



In [12]:
x=np.arange(20).reshape([4,5])

slices=np.array([2,3])

print()
print("slices = \n",slices)
print()


print()
print("x = \n",x)
print()

y=x[:,slices]

print()
print("y = \n",y)
print()

z=x[slices,:]
print()
print("z= \n",z)
print()


slices = 
 [2 3]


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


y = 
 [[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


z= 
 [[10 11 12 13 14]
 [15 16 17 18 19]]



In [13]:
x=np.arange(20).reshape(4,5)
print()
print("x = \n",x)
print()

w=np.diag(x)

print()
print("w = \n",w)
print()


v=np.diag(x,k=1)
print()
print("v = \n",v)
print()

b=np.diag(x,k=-1)
print()
print("b = \n",b)
print()



x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


w = 
 [ 0  6 12 18]


v = 
 [ 1  7 13 19]


b = 
 [ 5 11 17]



In [14]:
# practice slicing
x=np.arange(20).reshape((5,4))

print()
print("x = \n",x)
print()

w=x[2:5,2:4]


print()
print("w = \n",w)
print()

v=x[2:,2:4]


print()
print("v = \n",v)
print()

b=x[2:,2:]

print()
print("b = \n",b)
print()

w=x[2,:]

print()
print("w = \n",w)
print()

v=x[:,2]
print()
print("v = \n",v)
print()


x = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


w = 
 [[10 11]
 [14 15]
 [18 19]]


v = 
 [[10 11]
 [14 15]
 [18 19]]


b = 
 [[10 11]
 [14 15]
 [18 19]]


w = 
 [ 8  9 10 11]


v = 
 [ 2  6 10 14 18]



In [15]:
x=np.arange(24).reshape((4,6))

print()
print("x = \n",x)
print()

w=x[1:,2:]

print()
print("w = \n",w)
print()

w[2][3]=555

print()
print("w = \n",w)
print()


print()
print("x = \n",x)
print()


x = 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


w = 
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]]


w = 
 [[  8   9  10  11]
 [ 14  15  16  17]
 [ 20  21  22 555]]


x = 
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 555]]



In [16]:
x=np.arange(24).reshape(6,4)
print()
print("x = \n",x)
print()


w=np.copy(x[1:,2:])

print()
print("w = \n",w)
print()

w[2][1]=555

print()
print("w = \n",w)
print()

print()
print("x = \n",x)
print()


x = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


w = 
 [[ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]


w = 
 [[  6   7]
 [ 10  11]
 [ 14 555]
 [ 18  19]
 [ 22  23]]


x = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [17]:
x=np.arange(24).reshape(6,4)
print()
print("x = \n",x)
print()


w=x[1:,2:].copy()

print()
print("w = \n",w)
print()

w[2][1]=555

print()
print("w = \n",w)
print()

print()
print("x = \n",x)
print()



x = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


w = 
 [[ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]


w = 
 [[  6   7]
 [ 10  11]
 [ 14 555]
 [ 18  19]
 [ 22  23]]


x = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [18]:
x=np.arange(20).reshape([4,5])

print()
print("x = \n",x)
print()

indices=[1,3]

w=x[indices,:]

print()
print("w = \n",w)
print()

v=x[:,indices]

print()
print("v = \n",v)
print()


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


w = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]


v = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]



In [19]:
x=np.arange(20).reshape(4,5)

print()
print("x = \n",x)
print()

w=np.diag(x)

print()
print("w = \n",w)
print()

v=np.diag(x,k=1)

print()
print("v = \n",v)
print()
b=np.diag(x,k=-1)

print()
print("b = \n",b)
print()


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


w = 
 [ 0  6 12 18]


v = 
 [ 1  7 13 19]


b = 
 [ 5 11 17]



In [30]:


# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
x = np.arange(1,26).reshape(5,5)




print()
print("x = \n",x)
print()

# Use Boolean indexing to pick out only the odd numbers in the array
y = x[x%2!=0]


print()
print("y = \n",y)
print()


x = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


y = 
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]

