In [2]:
import numpy as np

In [3]:
x=np.arange(20).reshape((4,5))

print()
print("x = \n",x)
print()


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [9]:
z=x[1:4,2:5]

print()
print("z = \n",z)
print()


z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



In [10]:
z=x[1:,2:]
print()
print("z = \n",z)
print()


z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



In [11]:
z=x[1:,2:5]
print()
print("z = \n",z)
print()


z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



In [12]:
v=x[2,:]
print()
print("v = \n",v)
print()


v = 
 [10 11 12 13 14]



In [13]:
c=x[:,3]

print()
print("c = \n",c)
print()


c = 
 [ 3  8 13 18]



In [14]:
b=x[:,2]

print()
print("b = \n",b)
print()


b = 
 [ 2  7 12 17]



In [15]:
r=x[:,2:3]
print()
print("r = \n",r)
print()


r = 
 [[ 2]
 [ 7]
 [12]
 [17]]



In [18]:
x=np.arange(20).reshape(4,5)

print()
print("x = \n",x)
print()

z=x[1:4,2:5]

print()
print("z = \n",z)
print()

z[2][2]=555

print()
print("x = \n",x)
print()


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


x = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



In [21]:
x=np.arange(20).reshape(4,5)

z=np.copy(x[1:,2:5])
z[2][2]=555

v=x[1:4,2:5].copy()
v[2][2]=444

print()
print("x = \n",x)
print()

print()
print("z = \n",z)
print()

print()
print("v = \n",v)
print()



x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


v = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]



In [28]:
x=np.arange(20).reshape([4,5])

slices=np.array([2,3])

print()
print("slices = \n",slices)
print()


print()
print("x = \n",x)
print()

y=x[:,slices]

print()
print("y = \n",y)
print()

z=x[slices,:]
print()
print("z= \n",z)
print()


slices = 
 [2 3]


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


y = 
 [[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


z= 
 [[10 11 12 13 14]
 [15 16 17 18 19]]



In [33]:
x=np.arange(20).reshape(4,5)
print()
print("x = \n",x)
print()

w=np.diag(x)

print()
print("w = \n",w)
print()


v=np.diag(x,k=1)
print()
print("v = \n",v)
print()

b=np.diag(x,k=-1)
print()
print("b = \n",b)
print()



x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


w = 
 [ 0  6 12 18]


v = 
 [ 1  7 13 19]


b = 
 [ 5 11 17]

